export const constant = {
    LOGIN_REQUEST : "LOGIN_REQUEST_INITIATED",
    LOGIN_SUCCESSFUL : "LOGIN_REQUEST_SUCCESFUL",
    LOGIN_FAILURE : "LOGIN_FAILURE",
    VERIFY_OTP : "VERIFY_OTP_REQUEST_INITIATED",
    VERIFY_OTP_SUCCESSFUL : "VERIFY_OTP_SUCCESSFUL",
    VERIFY_OTP_FAILURE : "VERIFY_OTP_FAILURE",
    REGISTERATION_REQUEST : "REGISTRATION_REQUEST_INITIATED",
    REGISTRATION_SUCCESSFUL : "REGISTRATION_REQUEST_SUCCESSFUL",
    REGISTRATION_FAILURE : "REGISTRATION_REQUEST_FAILURE"
}